---
language: node_js


node_js:
  - "8"
  - "10"

branches:
  only:
  - master
  - dev

before_install:
  - npm uninstall
  - npm cache clean --force
  - rm -rf node_modules

install:
  - npm install

cache:
  npm: false

script:
  - npm --version
  - npm run lint
  - npm run test:unit