---
language: node_js

node_js: lts/*

branches:
  only:
  - master
  - dev

install:
  - rm -rf node_modules
  - npm install

cache:
  npm: false

script:
  - npm --version
  - npm run lint
  - npm run test:unit